config/routes.rb
Rails.application.routes.draw do

  root 'items#index' # root = index du site = page index des items
  get '/:locale' => 'items#index'

  scope '/:locale', locale: /#{I18n.available_locales.join("|")}/ do
    resources :items
    resources :users, except: [:edit, :update, :index]
  end

end

app/models/item.rb
##
# Model pour les items
class Item < ActiveRecord::Base
  belongs_to :user
  delegate :nom, to: :user, prefix: true # provides a delegate class method to easily expose contained objects' public methods as your own

  # ajout de la gem friendlyId pour generer les liens permanents
  extend FriendlyId
  friendly_id :titre, use: [:slugged, :finders] # finders: pour la methode find dans le controller en fonction de id de objet

  has_attached_file :image, styles: { medium: '300x300', thumb: '100x100', crop: '200x200#' }, default_url: '/images/:style/missing.png'
  validates_attachment :image, presence: { message: 'image obligatoire' }, content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] }

  # validates :titre, presence: true, length: { maximum: 25, message: 'titre trop long'}
  # validates :titre, :presence => true, :length => { :maximum => 25, :message => 'titre trop long'}
  validates :titre, presence: { message: 'titre obligatoire' }, length: { maximum: 25, message: 'titre trop long' }
  validates :contenu, presence: { message: 'contenu obligatoire' }
  # validates :image, presence: true
end

app/models/user.rb
##
# Email validator
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || 'pas au bon format') unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

##
# Model pour les User
class User < ActiveRecord::Base
  # associations
  has_many :items, dependent: :destroy

  # ajout de la gem friendlyId pour generer les liens permanents
  extend FriendlyId
  friendly_id :nom, use: [:slugged, :finders] # finders: pour la methode find dans le controller en fonction de id de objet

  # validations
  validates :nom, presence: { message: 'nom obligatoire' }, length: { maximum: 20, message: 'nom trop long' }
  validates :email, presence: { message: 'email obligatoire' }, uniqueness: true, email: true
  # validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
##
# Controller de l'application
class ApplicationController < ActionController::Base
  before_action :set_locale

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # definit la variable locale
  # soit le param passe dans url
  # soit la variable du fichier de conf
  def set_locale
    # I18n.locale = params[:locale] || I18n.default_locale
    # I18n.locale = (['fr', 'en'].include?(params[:locale])) ? params[:locale] : I18n.default_locale
    I18n.locale = (%w(fr en).include?(params[:locale])) ? params[:locale] : I18n.default_locale
  end

  # ajout la variable locale a url
  # http://localhost:3000/items/new?locale=fr
  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/items_controller.rb
##
# Controller pour les items
class ItemsController < ApplicationController
  def index
    # @items = Item.all
    @items = Item.paginate(page: params[:page_item], per_page: 3)
    @users = User.paginate(page: params[:page_user], per_page: 5)
    # Rails.logger.debug("items = #{@items.nil?}")
  end

  def new
    @item = Item.new
    @users = User.all
    # Rails.logger.debug("erreur = #{@item.errors.messages.nil?}")
  end

  def create
    @item = Item.new(item_params)
    @item.image = params[:item][:image]

    # @item.titre = "#{item_params[:titre]}"
    # @item.contenu = "#{item_params[:contenu]}"
    # @item.image = "/items/#{item_params[:image].original_filename}" unless item_params[:image].nil?

    if @item.save
      # render "index"
      # redirect_to "index"
      # redirect_to @item

      # if File.exist?("public/items/#{item_params[:image].original_filename}")
      #  FileUtils.rm("public/items/#{item_params[:image].original_filename}")
      # end
      # FileUtils.cp item_params[:image].tempfile, "public/items/#{item_params[:image].original_filename}"

      redirect_to root_path, flash: { notice: 'Insertion OK!!!' }
    else
      # Rails.logger.debug("erreur = #{@item.errors.messages}")
      # Rails.logger.debug("erreur = #{@item.errors.full_messages}")
      # Rails.logger.debug("erreur = #{@item.errors.messages.nil?}")
      render 'new'
      # redirect_to root_path, flash: { alert: "ERREUR !!!" }
    end
  end

  def show
    @item = Item.find(params[:id])
    # Rails.logger.debug("items = #{@item.inspect}")
  end

  def destroy
    @item = Item.find(params[:id])
    # Rails.logger.debug("items#DELETE = #{@item.inspect}")
    # if File.exist?("public#{@item.image}") && FileUtils.rm("public#{@item.image}") && @item.destroy
    if @item.destroy
      # Rails.logger.debug("items#DELETE SUPPRESSION DE IMAGE")
      redirect_to root_path, flash: { notice: t('notice.delete_item') }
    else
      redirect_to root_path, flash: { alert: t('alert.delete_item') }
    end
  end

  def edit
    @item = Item.find(params[:id])
    # Rails.logger.debug("items#edit = #{@item.inspect}")
    @users = User.all
  end

  def update
    @item = Item.find(params[:id])

    # Rails.logger.debug("items#update = #{@item.inspect}")
    # Rails.logger.debug("items#update params = #{params}")
    # Rails.logger.debug("items#update item_params = #{item_params}")

    # @item.titre = "#{item_params[:titre]}"
    # @item.contenu = "#{item_params[:contenu]}"

    # unless item_params[:image].nil?
    #  @item.image = "/items/#{item_params[:image].original_filename}"

    #  if File.exist?("public/items/#{item_params[:image].original_filename}")
    #    FileUtils.rm("public/items/#{item_params[:image].original_filename}")
    #  end
    #  FileUtils.cp item_params[:image].tempfile, "public/items/#{item_params[:image].original_filename}"
    # end

    # if @item.save
    if @item.update(item_params)
      redirect_to root_path, flash: { notice: t('notice.update_item') }
    else
      render 'edit'
      # redirect_to root_path, flash: { alert: "ERREUR modif item !!!" }
    end
  end

  private

  def item_params # a partir de Rails 4
    params.require(:item).permit(:titre, :contenu, :image, :slug, :user_id)
  end
end

app/controllers/users_controller.rb
##
# Controller pour les utilisateurs
class UsersController < ApplicationController
  ##
  # Page pour la création d'un nouvel utilisateur
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path, flash: { notice: t('notice.delete_user') }
    else
      redirect_to root_path, flash: { alert: t('alert.delete_user') }
    end
  end

  private

  def user_params
    params.require(:user).permit(:nom, :email, :slug)
  end
end

app/helpers/application_helper.rb
##
# Helper pour Application
module ApplicationHelper
end

app/views/items/edit.html.erb
<h2>Modifier un item</h2>

<% unless @item.errors.messages.nil? %>
	<% @item.errors.messages.each do |key, val|  %>
		<h5 style='color: #900'><%= "#{key} #{val}" %></h5>
	<% end %>
<% end %>

<!-- peut etre mis dans un fichier html seul pour être réutiliser sur plusieurs pages (app/views/shared/_error.html.erb) -->
<% unless @item.errors.full_messages.nil? %>
	<% @item.errors.full_messages.each do |mess|  %>
		<h5 style='color: #900'><%= "#{mess}" %></h5>
	<% end %>
<% end %>

<%= form_for @item do |f| %>
	<%= f.label :titre %>
	<%= f.text_field :titre %><br />
	<%= f.label :contenu %>
	<%= f.text_area :contenu %><br />
	<%= f.label :image %>
	<%= f.file_field :image %><br />
	<% unless @item.image.nil? %>
		<%= image_tag(@item.image, width: '50') %><br />
	<% end %>
    <%= f.select(:user_id) do %>
        <%= options_from_collection_for_select(User.all, :id, :nom, selected: @item.user.id) %>
    <% end %>
    <br />
	<%= f.submit "Modifier" %>
<% end %>

app/views/items/index.html.erb
<div>
	<!-- flash: à mettre dans un fichier seul -->
	<% if flash.key?("notice") %>
		<p id="notice"><%= notice %></p>
	<% end %>
	<% if flash.key?("alert") %>
		<p id="alert"><%= alert %></p>
	<% end %>
	<!-- <pre><%= session.inspect.to_yaml %></pre> -->
	<% if @items.length == 0 %>
		<%= t('txt.no_item') %><br />
		<%= link_to t('link.create_item'), new_item_path %>
	<% else %>
		<%= t('txt.my_item') %>&nbsp;(<%= @items.count %>)
		<table border=1>
			<tr>
				<th><%= t('table.th.id_item') %></th>
				<th><%= t('table.th.title_item') %></th>
				<th><%= t('table.th.content_item') %></th>
				<th><%= t('table.th.image_item') %></th>
				<th><%= t('table.th.user_item') %></th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
			</tr>
			<% @items.each do |item| %>
				<tr>
					<td><%= item.id %></td>
					<td><%= link_to item.titre,  item %></td>
					<td><%= item.contenu %></td>
					<td><%= image_tag(item.image.url(:thumb)) %></td>
					<td><%= item.user_nom %></td>
					<td><%= link_to image_tag('edit.png', alt: t('link.change_item'), title: t('link.change_item')), edit_item_path(item.id) %>
					<td><%= link_to image_tag('delete.png', alt: t('link.delete_item'), title: t('link.delete_item')), item_path(item.id), method: :delete, data: { confirm: t('confirm.delete_item') } %>
				</tr>
			<% end %>
		</table>
		<%= will_paginate @items, :param_name => 'page_item' %>
	<% end %>
    <br />
	<% if @users.length == 0 %>
        <%= t('txt.no_user') %><br />
        <%= link_to t('link.create_user'), new_user_path %>
    <% else %>
        <%= t('txt.my_user') %>&nbsp;(<%= @users.count %>)
        <table border=1>
            <tr>
                <th><%= t('table.th.id_user') %></th>
                <th><%= t('table.th.name_user') %></th>
                <th><%= t('table.th.mail_user') %></th>
                <th><%= t('table.th.item_user') %></th>
                <th>&nbsp;</th>
            </tr>
            <% @users.each do |user| %>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= link_to user.nom, user %></td>
                    <td><%= user.email %></td>
                    <td>
                        <ul>
                            <% user.items.each do |user_item| %>
                                <li><%= user_item.titre %></li>
                            <% end %>
                        </ul>
                    </td>
                    <td><%= link_to image_tag('delete.png', alt: t('link.delete_user'), title: t('link.delete_user')), user_path(user.id), method: :delete, data: { confirm: t('confirm.delete_user') } %>
                </tr>
            <% end %>
        </table>
        <%= will_paginate @users, :param_name => 'page_user' %>
    <% end %>
</div>

app/views/items/new.html.erb
<h2><%= t('h2.add_item') %></h2>

<% unless @item.errors.messages.nil? %>
	<% @item.errors.messages.each do |key, val|  %>
		<h5 style='color: #900'><%= "#{key} #{val}" %></h5>
	<% end %>
<% end %>

<!-- peut etre mis dans un fichier html seul pour être réutiliser sur plusieurs pages (app/views/shared/_error.html.erb) -->
<% unless @item.errors.full_messages.nil? %>
	<% @item.errors.full_messages.each do |mess|  %>
		<h5 style='color: #900'><%= "#{mess}" %></h5>
	<% end %>
<% end %>

<%= form_for @item do |f| %>
	<%= f.label :titre %>
	<%= f.text_field :titre %><br />
	<%= f.label :contenu %>
	<%= f.text_area :contenu %><br />
	<%= f.label :image %>
	<%= f.file_field :image %><br />
    <%= f.select(:user_id) do %>
        <% @users.each do |user| %>
            <%= content_tag(:option, user.nom, value: user.id) %>
        <% end %>
    <% end %><br />
	<%= f.submit t('button.add') %>
<% end %>

app/views/items/show.html.erb
<h2><%= t('h2.show_item') %> #<%= @item.id %></h2>
<div><%= @item.titre %></div>
<div style='border: 1px solid #888; margin-bottom: 4px'><%= simple_format(@item.contenu) %></div>
<% unless @item.image.nil? %>
	<div><%= image_tag(@item.image.url(:medium)) %></div>
<% end %>
<div><%= @item.user_nom %></div>

app/views/layouts/_footer.html.erb
<hr />
<footer><%= t('page_footer') %></footer>

app/views/layouts/_header.html.erb
<header>
    <%= "Params locale URL = #{params[:locale]} - Langue du site = #{I18n.locale}" %><br />
    <%= link_to 'FR', '/fr' %> - <%= link_to 'EN', '/en' %>
    <hr />
	<%= t('page_header') %><br />
	<%= t('hello') %><br />
	<%= l Time.now, format: :short %><br />
	<%= link_to t('home'), "/#{I18n.locale}" %> - <%= link_to t('link.create_item'), new_item_path %> - <%= link_to t('link.create_user'), new_user_path %>
</header>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TodoList</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<%= yield %>
		<%= render "layouts/footer" %>
	</body>
	<%= debug(params) if Rails.env.development? %>
</html>

app/views/users/new.html.erb
<h2><%= t('h2.add_user') %></h2>

<!-- peut etre mis dans un fichier html seul pour être réutiliser sur plusieurs pages (app/views/shared/_error.html.erb) -->
<% unless @user.errors.full_messages.nil? %>
    <% @user.errors.full_messages.each do |mess|  %>
        <h5 style='color: #900'><%= "#{mess}" %></h5>
    <% end %>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :nom %>
    <%= f.text_field :nom %><br />
    <%= f.label :email %>
    <%= f.text_field :email %><br />
    <%= f.submit t('button.add') %>
<% end %>

app/views/users/show.html.erb
<h2><%= t('h2.show_user') %> #<%= @user.id %></h2>
<div><%= @user.nom %></div>
<div><%= @user.email %></div>